---
title: "To Tidymodel or not to Tidymodel, that this the question"
subtitle: "Workshop: How to get the most out of Tidymodeling with R"
author: "Henry Baker, add group"
date: "`r Sys.Date()`" 
output: 
  ioslides_presentation:
    widescreen: true
    smaller: true
    css: styles.css 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lattice)
library(ggplot2)
```

---



```{r, echo=FALSE}
# non-visible 
set.seed(123) 

synthetic_data <- data.frame(
  predictor1 = rnorm(100),  
  predictor2 = rnorm(100),  
  predictor3 = rnorm(100),  
  control1 = sample(c("Yes", "No"), 100, replace = TRUE), 
  control2 = runif(100), 
  outcome = rnorm(100)  
)

synthetic_data$outcome <- with(synthetic_data, predictor1 + 2*predictor2 + rnorm(100))

```

```{r}
model <- lm(outcome ~ predictor1 + predictor2 + predictor3 + control1 + control2, data=synthetic_data)
summary(model)
```





---
--

In these three cases, separate groups of developers devised three distinct interfaces for the same task. Each has advantages and disadvantages.

In comparison, the Python Developer’s Guide espouses the notion that, when approaching a problem:
“There should be one – and preferably only one – obvious way to do it.”


## A little motivation: why Tidymodels?
